apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo-app.fullname" . }}-service
  labels:
    {{- include "neo-app.labels" . | nindent 4 }}
  annotations:
    {{- include "neo-app.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "neo-app.selectorLabels" . | nindent 4 }}